pipeline:

  dependencies:
    image: node:alpine
    commands:
      - 'yarn install'

  build:
    image: node:alpine
    commands:
      - 'yarn build'

  test:
    image: node:alpine
    commands:
      - 'yarn test'

  publish:
    image: plugins/npm
    secrets: [ npm_username, npm_password ]
    email: dean@ethicaljobs.com.au
    when:
      status: success
      event: tag

  notify-slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: deployments
